channels:
- conda-forge
dependencies:
- python=3.9.24
- pip<=25.2
- pip:
  - mlflow==3.1.4
  - numpy==1.26.4
  - pandas==2.3.3
  - psutil==5.9.8
  - scikit-learn==1.6.1
  - scipy==1.13.1
  - xgboost==2.1.4
name: mlflow-env
